version: '3'
services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 8081:8081    
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    container_name: mongo_db
    network_mode: host
    volumes: 
      - ~/mongo/data:/data/db

  block_service:
    build: ./
    image: block_service
    restart: always
    container_name: block_service
    # environment:
    #   - DBUSER=root
    #   - DBPWD=example
    #   - DBURL=127.0.0.1
    #   - DBPORT=8181
    #   - DBNAME=blockservice
    network_mode: host


# volumes:
#   rocketswap-volume:
networks:
  block-service-network:
    driver: bridge
