version: '3.4'
services:

  block_service:
    build: ./
    image: block_service
    restart: always
    container_name: block_service

    environment:
      - DBUSER=
      - DBPWD=
      - DBURL=127.0.0.1
      - DBPORT=27017
      - NETWORK=mainnet
    network_mode: host