version: '3'
services:

  block_service:
    build: ./
    image: block_service
    restart: always
    container_name: block_service
    ports:
      - 3535:3535  
      - 3536:3536  
    # environment:
    #   - DBUSER=root
    #   - DBPWD=example
    #   - DBURL=127.0.0.1
    #   - DBPORT=8181
    #   - DBNAME=blockservice
    network_mode: host